/**
 * Created by shreyas on 8/27/15.
 */

(function() {

    'use strict';

    angular.module('uxApp',[]);

    angular.module('uxApp').controller('MainController',MainController);

    MainController.$inject = ["$http"];

    function MainController($http) {
        var mainVm = this;

        mainVm.displayPerson = null;

        mainVm.displayImage = null;

        mainVm.hide = true;

        mainVm.hideLoadMessage = false;
        mainVm.hideDataDiv = true;

        mainVm.clicked = function(p) {
            mainVm.displayPerson = p;

            if(p.gender === 'male') {
                mainVm.displayImage = 'images/icon_male.png';
            } else if(p.gender === 'female') {
                mainVm.displayImage = 'images/icon_female.png';
            }

            mainVm.hide = false;
        };

        $http.get('http://private-a73e-aquentuxsociety.apiary-mock.com/members').then(
            function(response) {
                mainVm.people = response.data;
                mainVm.hideLoadMessage = true;
                mainVm.hideDataDiv = false;
                mainVm.searchInput = '';
            }
        );
        console.dir(mainVm.people);


            /*[{
            "id":1,
            "gender":"male",
            "title":"Mr.",
            "firstName":"Ernesto",
            "middleInitial":"J",
            "surname":"Theroux",
            "streetAddress":"3426 Christie Way",
            "city":"Bedford",
            "state":"MA",
            "zipCode":"1730",
            "country":"United States",
            "email":"ErnestoJTheroux@dayrep.com",
            "username":"Himeacerhe",
            "birthday":"1/15/1968",
            "occupation":"Stevedore",
            "company":"Briazz",
            "latitude":"42.418043",
            "longitude":"-71.346313",
            "motto":"640K ought to be enough for anybody. (Bill Gates, 1981)",
            "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
        },
            {
                "id":2,
                "gender":"female",
                "title":"Mrs.",
                "firstName":"Tammie",
                "middleInitial":"D",
                "surname":"Kitchens",
                "streetAddress":"4763 Passaic Street",
                "city":"Washington",
                "state":"DC",
                "zipCode":"20036",
                "country":"United States",
                "email":"TammieDKitchens@fleckens.hu",
                "username":"Allichere",
                "birthday":"8/6/1954",
                "occupation":"Tax assessor",
                "company":"La Petite Boulangerie",
                "latitude":"38.869451",
                "longitude":"-77.029803",
                "motto":"A newspaper is a collection of half-injustices",
                "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
            },
            {
                "id":3,
                "gender":"male",
                "title":"Mr.",
                "firstName":"Douglas",
                "middleInitial":"C",
                "surname":"Secrist",
                "streetAddress":"3601 Little Street",
                "city":"Akron",
                "state":"OH",
                "zipCode":"44311",
                "country":"United States",
                "email":"DouglasCSecrist@fleckens.hu",
                "username":"Domence",
                "birthday":"10/25/1989",
                "occupation":"Diagnostic medical sonographer",
                "company":"First Rate Choice",
                "latitude":"41.069696",
                "longitude":"-81.505841",
                "motto":"All my hidden skills are undiscovered. - Clinton",
                "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
            },
            {
                "id":4,
                "gender":"female",
                "title":"Mrs.",
                "firstName":"Lydia",
                "middleInitial":"C",
                "surname":"Lee",
                "streetAddress":"1015 Irish Lane",
                "city":"Monroe",
                "state":"WI",
                "zipCode":"53566",
                "country":"United States",
                "email":"LydiaCLee@gustr.com",
                "username":"Theeng1946",
                "birthday":"8/19/1946",
                "occupation":"Financial economist",
                "company":"Reliable Guidance",
                "latitude":"42.537259",
                "longitude":"-89.610218",
                "motto":"Are your cookies made with real Girl Scouts?",
                "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
            },
            {
                "id":5,
                "gender":"female",
                "title":"Ms.",
                "firstName":"Kirstin",
                "middleInitial":"L",
                "surname":"Miller",
                "streetAddress":"3528 Waldeck Street",
                "city":"Dallas",
                "state":"TX",
                "zipCode":"75247",
                "country":"United States",
                "email":"KirstinLMiller@teleworm.us",
                "username":"Mity1974",
                "birthday":"11/3/1974",
                "occupation":"Power dispatcher",
                "company":"Woolf Brothers",
                "latitude":"32.815473",
                "longitude":"-96.897678",
                "motto":"But honey, we need a 2 gig drive for word processing!",
                "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
            },
            {
                "id":6,
                "gender":"male",
                "title":"Mr.",
                "firstName":"David",
                "middleInitial":"V",
                "surname":"Burlison",
                "streetAddress":"2279 Matthews Street",
                "city":"Sterling",
                "state":"IL",
                "zipCode":"61081",
                "country":"United States",
                "email":"DavidVBurlison@armyspy.com",
                "username":"Perclovery",
                "birthday":"5/8/1992",
                "occupation":"Radio operator",
                "company":"William Wanamaker & Sons",
                "latitude":"41.745624",
                "longitude":"-89.802821",
                "motto":"DOS=HIGH Hmm, I knew it was on something...",
                "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
            },
            {
                "id":7,
                "gender":"male",
                "title":"Mr.",
                "firstName":"Vance",
                "middleInitial":"R",
                "surname":"Warren",
                "streetAddress":"663 Clinton Street",
                "city":"Searcy",
                "state":"AR",
                "zipCode":"72143",
                "country":"United States",
                "email":"VanceRWarren@rhyta.com",
                "username":"Miseen1970",
                "birthday":"12/17/1970",
                "occupation":"Engineering manager",
                "company":"Mr Fables",
                "latitude":"35.174471",
                "longitude":"-91.739357",
                "motto":"Good morning! is an opinion, not a greeting.",
                "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
            },
            {
                "id":8,
                "gender":"female",
                "title":"Mrs.",
                "firstName":"Deborah",
                "middleInitial":"C",
                "surname":"Coburn",
                "streetAddress":"3500 Echo Lane",
                "city":"Grand Rapids",
                "state":"MI",
                "zipCode":"49503",
                "country":"United States",
                "email":"DeborahCCoburn@jourrapide.com",
                "username":"Betheareast",
                "birthday":"4/22/1962",
                "occupation":"Finance officer",
                "company":"Veramons",
                "latitude":"42.999021",
                "longitude":"-85.576485",
                "motto":"Graphic Artist seeks Boss with vision impairment.",
                "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
            },
            {
                "id":9,
                "gender":"female",
                "title":"Mrs.",
                "firstName":"Gladys",
                "middleInitial":"M",
                "surname":"Warnock",
                "streetAddress":"2498 Dola Mine Road",
                "city":"Durham",
                "state":"NC",
                "zipCode":"27707",
                "country":"United States",
                "email":"GladysMWarnock@cuvox.de",
                "username":"Magning1945",
                "birthday":"6/30/1945",
                "occupation":"Engineer",
                "company":"Newmark & Lewis",
                "latitude":"36.003132",
                "longitude":"-78.873303",
                "motto":"Ground Beef -- A Cow With No Legs!",
                "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
            },
            {
                "id":10,
                "gender":"male",
                "title":"Mr.",
                "firstName":"David",
                "middleInitial":"R",
                "surname":"Thompson",
                "streetAddress":"231 Jefferson Street",
                "city":"Virginia Beach",
                "state":"VA",
                "zipCode":"23455",
                "country":"United States",
                "email":"DavidRThompson@cuvox.de",
                "username":"Snate1936",
                "birthday":"3/20/1936",
                "occupation":"Electronic home entertainment equipment repairer",
                "company":"Monk House Sales",
                "latitude":"36.813435",
                "longitude":"-76.152001",
                "motto":"Hex Dump - Where Witches put used curses?",
                "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
            },
            {
                "id":11,
                "gender":"female",
                "title":"Mrs.",
                "firstName":"Maria",
                "middleInitial":"C",
                "surname":"Myers",
                "streetAddress":"1680 Dovetail Estates",
                "city":"Tupelo",
                "state":"OK",
                "zipCode":"74572",
                "country":"United States",
                "email":"MariaCMyers@rhyta.com",
                "username":"Frated85",
                "birthday":"2/25/1985",
                "occupation":"Radiation therapist",
                "company":"Gemco",
                "latitude":"34.673143",
                "longitude":"-96.452543",
                "motto":"I'd like all your $20 bills in this bag, \"To go\".",
                "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
            },
            {
                "id":12,
                "gender":"female",
                "title":"Ms.",
                "firstName":"Diana",
                "middleInitial":"A",
                "surname":"Garza",
                "streetAddress":"505 Conifer Drive",
                "city":"Seattle",
                "state":"WA",
                "zipCode":"98122",
                "country":"United States",
                "email":"DianaAGarza@cuvox.de",
                "username":"Terew1978",
                "birthday":"5/18/1978",
                "occupation":"Account clerk",
                "company":"Standard Food",
                "latitude":"47.57336",
                "longitude":"-122.35858",
                "motto":"Leave my blouse alone! I said Spellcheck, not Spillcheck",
                "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
            },
            {
                "id":13,
                "gender":"male",
                "title":"Mr.",
                "firstName":"Philip",
                "middleInitial":"J",
                "surname":"Vaughn",
                "streetAddress":"172 Quilly Lane",
                "city":"Columbus",
                "state":"OH",
                "zipCode":"43219",
                "country":"United States",
                "email":"PhilipJVaughn@jourrapide.com",
                "username":"Inne1984",
                "birthday":"3/17/1984",
                "occupation":"Professor",
                "company":"Electric Avenue",
                "latitude":"40.035256",
                "longitude":"-82.862775",
                "motto":"MEOW...SPLAT...\"RUFF\"...SPLAT...(Raining cats & dogs)",
                "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
            },
            {
                "id":14,
                "gender":"female",
                "title":"Ms.",
                "firstName":"Helene",
                "middleInitial":"T",
                "surname":"Benjamin",
                "streetAddress":"1321 Stone Lane",
                "city":"West Chester",
                "state":"PA",
                "zipCode":"19382",
                "country":"United States",
                "email":"HeleneTBenjamin@fleckens.hu",
                "username":"Betied",
                "birthday":"11/13/1978",
                "occupation":"Occupational health nurse",
                "company":"Just For Fun",
                "latitude":"39.917502",
                "longitude":"-75.618456",
                "motto":"Please return stewardess to original upright position",
                "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
            },
            {
                "id":15,
                "gender":"female",
                "title":"Mrs.",
                "firstName":"Sarah",
                "middleInitial":"C",
                "surname":"Newman",
                "streetAddress":"149 Burnside Avenue",
                "city":"Saint George",
                "state":"UT",
                "zipCode":"84770",
                "country":"United States",
                "email":"SarahCNewman@gustr.com",
                "username":"Thignot",
                "birthday":"3/19/1957",
                "occupation":"Employee benefits specialist",
                "company":"Kelly and Cohen",
                "latitude":"37.231806",
                "longitude":"-113.673907",
                "motto":"Sometimes a cigar is just a cigar - Freud",
                "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
            },
            {
                "id":16,
                "gender":"female",
                "title":"Ms.",
                "firstName":"Pauline",
                "middleInitial":"A",
                "surname":"Hurst",
                "streetAddress":"2654 Hamill Avenue",
                "city":"La Mesa",
                "state":"CA",
                "zipCode":"91941",
                "country":"United States",
                "email":"PaulineAHurst@teleworm.us",
                "username":"Fation",
                "birthday":"1/11/1982",
                "occupation":"Electrician",
                "company":"Elm Farm",
                "latitude":"32.737361",
                "longitude":"-116.925017",
                "motto":"Uh honey, a P5 with a 20 monitor is perfect for mail\"",
                "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
            },
            {
                "id":17,
                "gender":"female",
                "title":"Ms.",
                "firstName":"Violet",
                "middleInitial":"R",
                "surname":"McDowell",
                "streetAddress":"1301 Fannie Street",
                "city":"San Angelo",
                "state":"TX",
                "zipCode":"76903",
                "country":"United States",
                "email":"VioletRMcDowell@cuvox.de",
                "username":"Repask",
                "birthday":"12/18/1942",
                "occupation":"Clerical specialist",
                "company":"Briazz",
                "latitude":"31.499164",
                "longitude":"-100.376579",
                "motto":"WHO CARES where Carmen Sandiego is?",
                "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
            },
            {
                "id":18,
                "gender":"male",
                "title":"Mr.",
                "firstName":"Bruce",
                "middleInitial":"D",
                "surname":"Smith",
                "streetAddress":"510 Scenic Way",
                "city":"Golden",
                "state":"IL",
                "zipCode":"62339",
                "country":"United States",
                "email":"BruceDSmith@armyspy.com",
                "username":"Natied",
                "birthday":"4/30/1962",
                "occupation":"Public works inspector",
                "company":"Vibrant Man",
                "latitude":"40.107297",
                "longitude":"-90.990987",
                "motto":"(A)bort, (R)etry, (F)ail, (G)rab_Hammer",
                "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
            },
            {
                "id":19,
                "gender":"male",
                "title":"Mr.",
                "firstName":"Wayne",
                "middleInitial":"C",
                "surname":"Krueger",
                "streetAddress":"4680 Hidden Pond Road",
                "city":"Nashville",
                "state":"TN",
                "zipCode":"37201",
                "country":"United States",
                "email":"WayneCKrueger@einrot.com",
                "username":"Himantand",
                "birthday":"2/25/1994",
                "occupation":"Elevator inspector",
                "company":"Crown Books",
                "latitude":"36.242309",
                "longitude":"-86.773049",
                "motto":"*IT IS* documented, look under \"For Internal Use Only.\"",
                "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
            },
            {
                "id":20,
                "gender":"male",
                "title":"Mr.",
                "firstName":"Anthony",
                "middleInitial":"B",
                "surname":"Rodriguez",
                "streetAddress":"4125 Hemlock Lane",
                "city":"Harlingen",
                "state":"TX",
                "zipCode":"78550",
                "country":"United States",
                "email":"AnthonyBRodriguez@dayrep.com",
                "username":"Desichall",
                "birthday":"6/27/1974",
                "occupation":"Treasurer",
                "company":"McMahan's Furniture",
                "latitude":"26.21775",
                "longitude":"-97.768926",
                "motto":"......64..65...66...67...68...69... \"STOP RIGHT THERE!\"",
                "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
            },
            {
                "id":21,
                "gender":"female",
                "title":"Ms.",
                "firstName":"Britney",
                "middleInitial":"H",
                "surname":"Tejeda",
                "streetAddress":"4148 Gambler Lane",
                "city":"Channelview",
                "state":"TX",
                "zipCode":"77530",
                "country":"United States",
                "email":"BritneyHTejeda@armyspy.com",
                "username":"Witterlass",
                "birthday":"4/1/1988",
                "occupation":"Sewage treatment plant operator",
                "company":"Newhair",
                "latitude":"29.859355",
                "longitude":"-95.095106",
                "motto":"...and I betcha she can say it in 10 different languages!",
                "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
            },
            {
                "id":22,
                "gender":"male",
                "title":"Mr.",
                "firstName":"James",
                "middleInitial":"A",
                "surname":"Hannah",
                "streetAddress":"1692 Chandler Hollow Road",
                "city":"Pittsburgh",
                "state":"PA",
                "zipCode":"15217",
                "country":"United States",
                "email":"JamesAHannah@superrito.com",
                "username":"Lifying",
                "birthday":"5/26/1992",
                "occupation":"Aircraft rigging assembler",
                "company":"White Hen Pantry",
                "latitude":"40.442103",
                "longitude":"-79.936173",
                "motto":"...I love children!  They taste just like chicken.",
                "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
            },
            {
                "id":23,
                "gender":"male",
                "title":"Mr.",
                "firstName":"Alex",
                "middleInitial":"J",
                "surname":"Dawson",
                "streetAddress":"3522 Thompson Street",
                "city":"Anaheim",
                "state":"CA",
                "zipCode":"92805",
                "country":"United States",
                "email":"AlexJDawson@fleckens.hu",
                "username":"Thateled57",
                "birthday":"1/1/1957",
                "occupation":"Support staff clerk",
                "company":"Sunflower Market",
                "latitude":"33.747021",
                "longitude":"-118.000888",
                "motto":"...I multi-task, I read in the bathroom.",
                "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
            },
            {
                "id":24,
                "gender":"female",
                "title":"Mrs.",
                "firstName":"Patricia",
                "middleInitial":"M",
                "surname":"Gutierrez",
                "streetAddress":"2904 Sherwood Circle",
                "city":"Lafayette",
                "state":"LA",
                "zipCode":"70501",
                "country":"United States",
                "email":"PatriciaMGutierrez@teleworm.us",
                "username":"Woution",
                "birthday":"4/17/1938",
                "occupation":"Plant operator",
                "company":"Hill-Behan",
                "latitude":"30.206527",
                "longitude":"-91.890273",
                "motto":"...So simple a child could do it?  Go find me a child!",
                "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
            },
            {
                "id":25,
                "gender":"female",
                "title":"Ms.",
                "firstName":"Fawn",
                "middleInitial":"T",
                "surname":"Erwin",
                "streetAddress":"3631 Daffodil Lane",
                "city":"Herndon",
                "state":"VA",
                "zipCode":"22070",
                "country":"United States",
                "email":"FawnTErwin@einrot.com",
                "username":"Loody1995",
                "birthday":"4/14/1995",
                "occupation":"Workforce development specialist",
                "company":"Ruehl No. 925",
                "latitude":"39.010374",
                "longitude":"-77.413208",
                "motto":"1 + 2 = 3; Therefore, 4 + 5 = 6.",
                "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
            },
            {
                "id":26,
                "gender":"female",
                "title":"Mrs.",
                "firstName":"Angela",
                "middleInitial":"T",
                "surname":"Smith",
                "streetAddress":"4003 Fowler Avenue",
                "city":"Norcross",
                "state":"GA",
                "zipCode":"30093",
                "country":"United States",
                "email":"AngelaTSmith@cuvox.de",
                "username":"Safters",
                "birthday":"5/9/1949",
                "occupation":"Sports competitor",
                "company":"Strategic Profit",
                "latitude":"33.956668",
                "longitude":"-84.22411",
                "motto":"10 days and 18 messages later, \"Oh I understand now\"",
                "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
            },
            {
                "id":27,
                "gender":"female",
                "title":"Mrs.",
                "firstName":"Heather",
                "middleInitial":"R",
                "surname":"Jones",
                "streetAddress":"1194 Williams Avenue",
                "city":"Bakersfield",
                "state":"CA",
                "zipCode":"93307",
                "country":"United States",
                "email":"HeatherRJones@fleckens.hu",
                "username":"Inclaboy1970",
                "birthday":"3/17/1970",
                "occupation":"Endodontist",
                "company":"Schweggmanns",
                "latitude":"35.155375",
                "longitude":"-118.796314",
                "motto":"20 Dumb Blonds in freezer:  Frosted flakes.",
                "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
            },
            {
                "id":28,
                "gender":"male",
                "title":"Mr.",
                "firstName":"Andrew",
                "middleInitial":"B",
                "surname":"McDonald",
                "streetAddress":"2994 Marietta Street",
                "city":"Santa Rosa",
                "state":"CA",
                "zipCode":"95401",
                "country":"United States",
                "email":"AndrewBMcDonald@rhyta.com",
                "username":"Aftestood",
                "birthday":"10/12/1965",
                "occupation":"Pharmacy technician",
                "company":"Bombay Company",
                "latitude":"38.448689",
                "longitude":"-122.697674",
                "motto":"3 stages of sex: Tri-weekly, try weekly, try weakly.",
                "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
            },
            {
                "id":29,
                "gender":"female",
                "title":"Dr.",
                "firstName":"Emma",
                "middleInitial":"C",
                "surname":"Johnson",
                "streetAddress":"1843 Clarence Court",
                "city":"Fullerton",
                "state":"CA",
                "zipCode":"93632",
                "country":"United States",
                "email":"EmmaCJohnson@einrot.com",
                "username":"Himect",
                "birthday":"6/19/1966",
                "occupation":"Animal scientist",
                "company":"Farrell's Ice Cream Parlour",
                "latitude":"33.838104",
                "longitude":"-117.968466",
                "motto":"50 states, and I had to pick one of confusion...",
                "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
            },
            {
                "id":30,
                "gender":"male",
                "title":"Mr.",
                "firstName":"Johnnie",
                "middleInitial":"R",
                "surname":"Crouse",
                "streetAddress":"3956 Woodhill Avenue",
                "city":"Beltsville",
                "state":"MD",
                "zipCode":"20705",
                "country":"United States",
                "email":"JohnnieRCrouse@gustr.com",
                "username":"Comences",
                "birthday":"5/20/1933",
                "occupation":"Automotive glass installer",
                "company":"Record Bar",
                "latitude":"39.026115",
                "longitude":"-76.890679",
                "motto":"69, 714, 2112 : Sex, drugs, and Rock and Roll!",
                "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
            },
            {
                "id":31,
                "gender":"male",
                "title":"Mr.",
                "firstName":"Charlie",
                "middleInitial":"B",
                "surname":"Macklin",
                "streetAddress":"798 Bryan Avenue",
                "city":"Minneapolis",
                "state":"MN",
                "zipCode":"55406",
                "country":"United States",
                "email":"CharlieBMacklin@gustr.com",
                "username":"Postard1941",
                "birthday":"6/19/1941",
                "occupation":"Bellhop",
                "company":"Super Duper",
                "latitude":"44.908322",
                "longitude":"-93.238183",
                "motto":"74% of all statistics are made up on the spot",
                "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
            },
            {
                "id":32,
                "gender":"male",
                "title":"Mr.",
                "firstName":"Lewis",
                "middleInitial":"L",
                "surname":"Collins",
                "streetAddress":"4919 Joes Road",
                "city":"Castleton",
                "state":"NY",
                "zipCode":"12033",
                "country":"United States",
                "email":"LewisLCollins@teleworm.us",
                "username":"Morrect",
                "birthday":"11/24/1989",
                "occupation":"News reporter",
                "company":"Asiatic Solutions",
                "latitude":"43.675061",
                "longitude":"-73.152284",
                "motto":"89.6% of all statistics are wrong.",
                "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
            },
            {
                "id":33,
                "gender":"female",
                "title":"Ms.",
                "firstName":"Diana",
                "middleInitial":"R",
                "surname":"Webb",
                "streetAddress":"3514 Star Trek Drive",
                "city":"Pensacola",
                "state":"FL",
                "zipCode":"32505",
                "country":"United States",
                "email":"DianaRWebb@jourrapide.com",
                "username":"Prour1994",
                "birthday":"10/16/1994",
                "occupation":"Glazier",
                "company":"Standard Sales",
                "latitude":"30.438932",
                "longitude":"-87.251372",
                "motto":"A .45 beats a royal flush EVERY TIME",
                "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
            },
            {
                "id":34,
                "gender":"female",
                "title":"Mrs.",
                "firstName":"Freida",
                "middleInitial":"G",
                "surname":"Dolphin",
                "streetAddress":"3858 Sussex Court",
                "city":"Sandy",
                "state":"TX",
                "zipCode":"78665",
                "country":"United States",
                "email":"FreidaGDolphin@cuvox.de",
                "username":"Witimen",
                "birthday":"11/24/1959",
                "occupation":"Art director",
                "company":"Magik Gray",
                "latitude":"30.184833",
                "longitude":"-98.43976",
                "motto":"A big enough hammer can usually fix anything.",
                "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
            },
            {
                "id":35,
                "gender":"female",
                "title":"Ms.",
                "firstName":"Carole",
                "middleInitial":"D",
                "surname":"Shirey",
                "streetAddress":"1183 Smithfield Avenue",
                "city":"Amarillo",
                "state":"TX",
                "zipCode":"79101",
                "country":"United States",
                "email":"CaroleDShirey@teleworm.us",
                "username":"Arche1977",
                "birthday":"9/5/1977",
                "occupation":"Help-desk technician",
                "company":"Universo Realtors",
                "latitude":"35.121057",
                "longitude":"-101.916292",
                "motto":"A bird in the hand is a big mistake.",
                "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
            },
            {
                "id":36,
                "gender":"male",
                "title":"Mr.",
                "firstName":"Reginald",
                "middleInitial":"G",
                "surname":"Adams",
                "streetAddress":"2325 Victoria Court",
                "city":"Caribou",
                "state":"ME",
                "zipCode":"4736",
                "country":"United States",
                "email":"ReginaldGAdams@teleworm.us",
                "username":"Destoo",
                "birthday":"3/6/1950",
                "occupation":"Staff development specialist",
                "company":"Crafts Canada",
                "latitude":"46.859634",
                "longitude":"-68.06464",
                "motto":"A bird in the hand is better than one overhead!",
                "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
            },
            {
                "id":37,
                "gender":"male",
                "title":"Mr.",
                "firstName":"William",
                "middleInitial":"J",
                "surname":"Steele",
                "streetAddress":"1508 Jennifer Lane",
                "city":"Cary",
                "state":"NC",
                "zipCode":"27513",
                "country":"United States",
                "email":"WilliamJSteele@gustr.com",
                "username":"Trighom",
                "birthday":"10/2/1982",
                "occupation":"Automated systems librarian",
                "company":"Adaptaz",
                "latitude":"35.87162",
                "longitude":"-78.859009",
                "motto":"A career is a job that takes about 20 more hours a week.",
                "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
            },
            {
                "id":38,
                "gender":"male",
                "title":"Mr.",
                "firstName":"Daniel",
                "middleInitial":"J",
                "surname":"Starkey",
                "streetAddress":"2828 Gateway Road",
                "city":"Portland",
                "state":"OR",
                "zipCode":"97204",
                "country":"United States",
                "email":"DanielJStarkey@armyspy.com",
                "username":"Wastione",
                "birthday":"2/18/1952",
                "occupation":"Electronics engineer",
                "company":"Formula Gray",
                "latitude":"45.553714",
                "longitude":"-122.638121",
                "motto":"A clean desk is a sign of a cluttered desk drawer.",
                "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
            },
            {
                "id":39,
                "gender":"female",
                "title":"Ms.",
                "firstName":"Virginia",
                "middleInitial":"K",
                "surname":"Nugent",
                "streetAddress":"2310 Aspen Court",
                "city":"Boston",
                "state":"MA",
                "zipCode":"2115",
                "country":"United States",
                "email":"VirginiaKNugent@superrito.com",
                "username":"Rower1969",
                "birthday":"1/6/1969",
                "occupation":"Mathematician",
                "company":"Big Apple",
                "latitude":"42.278861",
                "longitude":"-71.073739",
                "motto":"A cynic smells flowers and looks for the casket.",
                "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
            },
            {
                "id":40,
                "gender":"female",
                "title":"Mrs.",
                "firstName":"Angela",
                "middleInitial":"C",
                "surname":"Wilson",
                "streetAddress":"1742 Butternut Lane",
                "city":"Renault",
                "state":"IL",
                "zipCode":"62279",
                "country":"United States",
                "email":"AngelaCWilson@dayrep.com",
                "username":"Thatentry",
                "birthday":"7/18/1956",
                "occupation":"Web designer",
                "company":"The Jolly Farmer",
                "latitude":"38.255409",
                "longitude":"-90.103593",
                "motto":"A dry sense of humor is better than slobbering everywhere",
                "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
            },
            {
                "id":41,
                "gender":"female",
                "title":"Mrs.",
                "firstName":"Carol",
                "middleInitial":"A",
                "surname":"Washington",
                "streetAddress":"464 John Avenue",
                "city":"Michigan Center",
                "state":"MI",
                "zipCode":"49254",
                "country":"United States",
                "email":"CarolAWashington@cuvox.de",
                "username":"Opeat1963",
                "birthday":"7/26/1963",
                "occupation":"Psychiatric technician",
                "company":"Your Future Is Now",
                "latitude":"42.196591",
                "longitude":"-84.360749",
                "motto":"A field upgrade,HAL. We're going to make you IBM compatible.",
                "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
            },
            {
                "id":42,
                "gender":"male",
                "title":"Mr.",
                "firstName":"Ernest",
                "middleInitial":"B",
                "surname":"Russ",
                "streetAddress":"2157 Goosetown Drive",
                "city":"Barnardsville",
                "state":"NC",
                "zipCode":"28709",
                "country":"United States",
                "email":"ErnestBRuss@rhyta.com",
                "username":"Caladving",
                "birthday":"7/27/1979",
                "occupation":"Employment manager",
                "company":"Enviro Architectural Designs",
                "latitude":"35.849653",
                "longitude":"-82.437014",
                "motto":"A fool with a tool is a well-equipped fool",
                "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
            },
            {
                "id":43,
                "gender":"female",
                "title":"Ms.",
                "firstName":"Alice",
                "middleInitial":"D",
                "surname":"Barr",
                "streetAddress":"750 Taylor Street",
                "city":"Fairview Park",
                "state":"NY",
                "zipCode":"10603",
                "country":"United States",
                "email":"AliceDBarr@einrot.com",
                "username":"Yessund1977",
                "birthday":"4/30/1977",
                "occupation":"Specialist",
                "company":"Matrix Architectural Service ",
                "latitude":"40.437126",
                "longitude":"-74.276259",
                "motto":"A girl a day keeps the wife away.",
                "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
            },
            {
                "id":44,
                "gender":"male",
                "title":"Mr.",
                "firstName":"Jordan",
                "middleInitial":"F",
                "surname":"Bryant",
                "streetAddress":"4777 Edgewood Avenue",
                "city":"Fresno",
                "state":"CA",
                "zipCode":"93721",
                "country":"United States",
                "email":"JordanFBryant@rhyta.com",
                "username":"Quablosom",
                "birthday":"4/6/1964",
                "occupation":"Attorney",
                "company":"Aaronson Furniture",
                "latitude":"36.731601",
                "longitude":"-119.852033",
                "motto":"A good marriage outlasts the first box of dental floss.",
                "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
            },
            {
                "id":45,
                "gender":"male",
                "title":"Mr.",
                "firstName":"Danny",
                "middleInitial":"Y",
                "surname":"Gray",
                "streetAddress":"1983 Payne Street",
                "city":"Houston",
                "state":"TX",
                "zipCode":"77062",
                "country":"United States",
                "email":"DannyYGray@teleworm.us",
                "username":"Eineve",
                "birthday":"9/2/1975",
                "occupation":"Fire investigator",
                "company":"Newmark & Lewis",
                "latitude":"29.619771",
                "longitude":"-95.198858",
                "motto":"A hundred years from now, none of us will give a damn.",
                "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
            },
            {
                "id":46,
                "gender":"female",
                "title":"Ms.",
                "firstName":"Patricia",
                "middleInitial":"J",
                "surname":"Kelly",
                "streetAddress":"2469 Village View Drive",
                "city":"Fort Myers",
                "state":"FL",
                "zipCode":"33905",
                "country":"United States",
                "email":"PatriciaJKelly@cuvox.de",
                "username":"Scove1989",
                "birthday":"2/26/1989",
                "occupation":"Transfer clerk",
                "company":"Profitpros",
                "latitude":"26.709202",
                "longitude":"-81.843432",
                "motto":"A husband is a lover who pushed his luck too far.",
                "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
            },
            {
                "id":47,
                "gender":"male",
                "title":"Mr.",
                "firstName":"Charles",
                "middleInitial":"R",
                "surname":"Wade",
                "streetAddress":"743 Ridenour Street",
                "city":"Miramar",
                "state":"FL",
                "zipCode":"33025",
                "country":"United States",
                "email":"CharlesRWade@dayrep.com",
                "username":"Thetut50",
                "birthday":"1/16/1950",
                "occupation":"Executive administrator",
                "company":"Buckeye Furniture",
                "latitude":"26.04803",
                "longitude":"-80.360752",
                "motto":"A jerk present in a group indicates a jerk in charge.",
                "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
            },
            {
                "id":48,
                "gender":"female",
                "title":"Mrs.",
                "firstName":"Nicole",
                "middleInitial":"R",
                "surname":"Petersen",
                "streetAddress":"1692 Science Center Drive",
                "city":"Boise",
                "state":"ID",
                "zipCode":"83702",
                "country":"United States",
                "email":"NicoleRPetersen@dayrep.com",
                "username":"Sudis1937",
                "birthday":"3/19/1937",
                "occupation":"Printmaker",
                "company":"Market Basket",
                "latitude":"43.649748",
                "longitude":"-116.120567",
                "motto":"A lawyer's opinion is worth nothing unless paid for.",
                "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
            },
            {
                "id":49,
                "gender":"male",
                "title":"Mr.",
                "firstName":"Andrew",
                "middleInitial":"E",
                "surname":"Green",
                "streetAddress":"3579 B Street",
                "city":"Saint Paul",
                "state":"MN",
                "zipCode":"55104",
                "country":"United States",
                "email":"AndrewEGreen@armyspy.com",
                "username":"Tuporat",
                "birthday":"3/1/1947",
                "occupation":"Pipelayer",
                "company":"Seamans Furniture",
                "latitude":"44.918525",
                "longitude":"-93.178429",
                "motto":"A little greed can get you lots of stuff",
                "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
            },
            {
                "id":50,
                "gender":"male",
                "title":"Mr.",
                "firstName":"Kelly",
                "middleInitial":"M",
                "surname":"Moore",
                "streetAddress":"612 Jefferson Street",
                "city":"Norfolk",
                "state":"VA",
                "zipCode":"23502",
                "country":"United States",
                "email":"KellyMMoore@gustr.com",
                "username":"Ouselece35",
                "birthday":"5/21/1935",
                "occupation":"Hospital attendant",
                "company":"Elek-Tek",
                "latitude":"36.802202",
                "longitude":"-76.157133",
                "motto":"A low yield atomic bomb is like being a bit pregnant.",
                "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
            },
            {
                "id":51,
                "gender":"male",
                "title":"Mr.",
                "firstName":"Kenneth",
                "middleInitial":"E",
                "surname":"McDaniel",
                "streetAddress":"4574 Ferry Street",
                "city":"Florence",
                "state":"AL",
                "zipCode":"35630",
                "country":"United States",
                "email":"KennethEMcDaniel@rhyta.com",
                "username":"Adbital",
                "birthday":"3/20/1993",
                "occupation":"Clinical dietitian",
                "company":"Rivera Property Maintenance",
                "latitude":"34.763069",
                "longitude":"-87.611873",
                "motto":"A man's incomplete until married; then he's finished!",
                "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
            },
            {
                "id":52,
                "gender":"male",
                "title":"Mr.",
                "firstName":"Erwin",
                "middleInitial":"S",
                "surname":"Marshall",
                "streetAddress":"3030 Irving Place",
                "city":"Stlouis",
                "state":"MO",
                "zipCode":"63101",
                "country":"United States",
                "email":"ErwinSMarshall@teleworm.us",
                "username":"Lifess",
                "birthday":"5/2/1991",
                "occupation":"Wealth manager",
                "company":"Rainbow Records",
                "latitude":"38.67245",
                "longitude":"-90.125389",
                "motto":"A narrow mind is usually accompanied by a wide mouth.",
                "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
            }];
            */
    }

})();
